### ISSUE TITLE
Feature request: Support downloading of past purchases

### ISSUE THREAD

**Issue by RichiH** [56north/Rmazon#1]
As per subject, it would be nice to be able to ingest data about past purchases as well.

**Comment by mikkelkrogsholm** [comment]
What do you mean? Your own past purchases?

If you log in you can probably get productcodes of all your purchases and the lapply your way through...

**Comment by RichiH** [comment]
Correct, your own purchases. This would, in turn, allow doing stats across years, months, etc. How much money do you spend at around 21:00 local on a Wednesday, etc.
